---
title: "AI Policy"
---

## General
- Add overview of the lab's general position
- Define scope as genAI, noting AI is a broad term with other applications.
- Acknowledge environmental and ethical considerations
Acknowledge that genAI is reshaping all fields and many aspects of life that we cannot ignore.
- Aim to identify where genAI can improve training and research while creating guardrails to avoid unintentional cognitive offloading and protect against false and inaccurate information. 
- Our policy should be guided by a principle of caution about what skills we are offloading onto AI. Building critical thinking, coding, and writing skills is essential and we need to be careful to hone those skills.
- Writing and coding are both essential parts of understanding a scientific problem. Working through the logic of each and exploring all avenues, even ones that become dead ends, is exactly part of the point.
- Approach to AI when learning skills vs. when trying to execute a task for a skill you already developed needs to be different
- Point about the skills students should walk away with, including being able to answer interview Q's about AI use. 
- Caution about slippery slope. 
- Caution about isolation. Turning to peers, mentors, and broader network is important for building community and networking is important professionally. 

## Rules
1. Cannot be used to generate your research question.  
2. Cannot be used for original writing claimed you author. 
3. You must be able to explain and justify every line of text or code in your final product. 
4. Carefully document any AI used in projects so it can be reported in any appropriate channels.

## Questions to ask before opening a GenAI tool
1. What is your objective? 
2. What other resources exist?
3. What information or output do you not want to receive?

## Writing
### Authored products
- Peer-reviewed publications, reports, thesis/dissertation chapters, proposals, etc.
- General principle: use for comments not line edits
- Consider prompts that take text you wrote and ask for bullet point feedback on it, rather than having it generate any text for you.
- Request multiple options for any requested summaries, shortening or editing to force yourself to critically evaluate the returned writing. 
- Should not be the sole source of feedback or input. Always consider who else in your network you can ask. 
- Be careful what data and information you give any AI-software, especially if it's for a proposal. Note ways to turn off data sharing. 
- Grammarly is helpful for editing, but it also offers rewording that makes it picked up by AI-detection software
- Note the special consideration for students for whom English is their second language. Translation and grammar improvement can be a huge benefit, but language development itself remains an important goal. Likely focus on prompting related to individual phrases or sentences rather than sections of text. Initial writing should still occur in English for those in our lab. 
- Refer to writing page for guide and resources related to building writing skills. 
- Important to develop and maintain your voice as a writer. 
- Can potentially use as a thought partner by asking it to push back on your ideas or logic. 
- Pull example prompts and reference [Carman 2025](https://medium.com/@TheWarOnBugs/keep-it-real-how-to-use-ai-without-losing-your-writing-voice-252c97c48e6e). 
- Can be useful as a search tool to find specific, relevant examples, but you still need to be careful to check sources and mindful of the risk of confirmation bias. 
- Can provide some text and request for feedback from different potential reviewer perspectives (e.g., ecologist, economist, etc.)
- Can request for a summary of the structure or visual representation to ensure your end product aligns with your intended logic. 
- Develop template coauthor agreement that specifies whether/how genAI is/can be used in the paper by any coauthors. Such a policy can also be suggested for use by papers led by external collaborators, though we cannot realistically force others to adopt an author agreement and it is ultimately very difficult to enforce.  

### Paper-associated products
- Summaries, conference abstracts, press releases, etc.
- Brainstorming title list or options for naming something (still don't rely on only one)

### Application materials
- Cover letters, essays, recommendation letters

### Administrative documents
- Standard forms, budget summaries, etc.

### Emails

## Coding
- The code author should be able to fully explain exactly what the code is doing and why particular choices were made.
- Approach AI as you would Stack Exchange.

### Logic versus syntax

### Code review and optimization

### Figures
- Possibly different guidance for data-based figures versus conceptual figures vs decorative figures (e.g., for presentations) and for generating figures versus editing/polishing figures. 
### Documentation

## GenAI tools as part of the research design
- We do computational work and there are undoubtedly many creative applications for AI to process messy data, scrape new data sources, etc. 
- Our lab is already involved in this work and this is a research frontier. 
- This is allowed, but the design needs to be intentional about avoiding undesirable mental offloading and cautious about the fact that these are new and rapidly evolving tools. 
- Like any tool or new method, using AI models as part of your research requires fully understanding the tool. 
- Note relevance of other AI tools (see [Norman et al. 2025](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/fee.70021)). 

## Literature review
- LLMs are more efficient at pulling sources from standard databases, can be a big time saver to gather relevant materials
- LLMs can scan PDFs rather than just relying on the metadata files, allowing them to do a better job at finding some information. 
- But, sometimes they make stuff up! Important to ALWAYS read the materials on your own with a critical eye

## Skills
- Background on what skills are and general guidance on how they can be used (with links to useful resources)
- Link to any skills we develop based on the above principles 

## Resources
