---
title: "Communication and Collaboration"
editor: 
  markdown: 
    wrap: sentence
---

## Slack

Slack is the primary lab communication space as it allows the entire lab and affiliated researchers to share information.
However, note that at the time of this writing, we use the free version of Slack, which does not preserve messages beyond 90 days.

Slack best practices:

-   Include tags where appropriate to draw attention to the relevant people.
-   Reply to individual posts as a thread so it is clear what the response goes to.
-   Post to public channels so all can weigh in and see the answers (others probably have the same question!).
-   Don't be shy about frequent posting or sharing interesting things - more regular sharing helps build community!
-   Acknowledge you have read a message (either a reply or emoji reaction is fine)

## Github issues and projects

FIXIT: @althea to add

## Email

Email is the preferred communication method for official business (e.g., communicating about funding, degrees, time off, etc.) because it can be referred back to beyond the 90-day limit of Slack.
Additionally, email is preferred for communication about projects and papers with external collaborators.

A few tips for email best practices:

-   Include a descriptive subject line (this makes searching easier in the future).
-   Keep each email focused on one specific subject - this helps avoid email threads from containing multiple separate conversations, which can become confusing and difficult to search for in the future.
-   Include hyperlinks wherever relevant/possible (especially to docs you want feedback on). This makes it easier for the recipients to access the information.
-   Be clear about any action items. Lists are often helpful.
-   Include deadlines. While the deadlines need to be reasonable, it is important so your busy collaborators can build your request into their workflow.
-   Include your name at the end of the message so it is clear where the message ends.
-   Reply to emails you receive in a timely fashion, even if only to say you need a bit longer to provide a full response.
-   Set an out of office message if you will be away or checking email less frequently than usual with a date you will return so recipients know when to expect a response by (and therefore, when to follow up, if needed).

## Google drive

We maintain a lab Google drive for sharing internal documents, including drafts of papers.
While students may use the platform of their choice for writing, Google docs generally remain the easiest for a range of collaborators to engage with, particularly if you anticipate receiving feedback from multiple individuals simultaneously (merging divergent drafts is no fun!).
Just be sure to set the sharing settings so that anyone with a link can edit, as long as there is not sensitive information, as this ensures that your collaborators will definitely have access to your doc when they need it.

## Individual meetings

Each student will start with a weekly individual meeting to provide progress updates and talk through outstanding issues.
These meetings should be led by the student.
To make the most of the time, it is often helpful to:

-   Send (via email or Slack) any documents that should be reviewed at least 24 hours in advance (longer is better if the doc is longer).
-   Create an agenda for the meeting with a list of updates, discussion points, and action items for each project:
    -   Updates should detail the current status of projects and what has been accomplished since the last meeting.
    -   Discussion points should be the main focus of the meeting. These should be specific questions or issues that are best resolved through an in person discussion. These are often related to conceptual issues, generating ideas, and sketching out solutions rather. You can of course include quick questions, but these can often be answered outside of the meeting via Slack (i.e., you don't need to wait until a weekly meeting to have them answered).
    -   Action items - these will likely emerge from the meeting, but it is good to include points here that you already know of because we can then review those along with any action items/next steps that emerged from the discussion to prioritize them.

Regardless of whether your meeting is within the lab or not, a bit of preparation ahead of the meeting will ensure it is productive.
This is ciritcal for ensuring that you get out of the meeting what you need and that you keep the other meeting attendees engaged with the work.

To ensure students are meeting their longer term goals, they will complete a [student goals form](https://docs.google.com/document/d/1ZFHLwgIyH5Q2NCY7qfXAO1J8xxvhQBDxssyZ_StP6SA/edit?usp=sharing) at the beginning of their degree and we will review this form annually.

Additionally, the graduate program has its own progress forms to ensure students remain on track.
Be sure to review the [SAFS Forms, Guidelines & Handbooks](https://fish.uw.edu/students/advising/forms-guidelines-handbooks/).

## Lab meetings

Once the lab is a sufficient size, we will hold regular lab meetings.
We will set the schedule for lab meetings at the beginning of each quarter.
Lab meetings will consist of a combination of paper discussions, professional development discussions, lab projects, and team member papers/presentations with feedback.
The exact mix will depend on lab needs and interests.
