---
title: "Seafood Globalization Lab Manual"
subtitle: "Tools, resources, background and more"
---

## Welcome {#welcome}

Welcome to the Seafood Globalization Lab! This website outlines and provides a high level overview of our values and relevant details to apply these values to how we operate as a lab. Please see the sections on the left hand navigation bar.

## Acknowledgements

The content in this manual draws from past and present lab member's experiences across many research teams and data/coding settings. We are also incorporating content the [Applied Ecology Lab's lab manual](https://scheuerell-lab.github.io/lab-book/index.html), which includes great content, including some UW/SAFS-specific information. from We would also like to thank our mentors and collaborators for the examples they have set, the conversations we have had, and the resources they have shared across many years. 

## Land acknowledgment
We acknowledge the ancestral homelands of those who walked here before us and those who still walk here, keeping in mind the integrity of this territory where area Native peoples identify as the Duwamish, Suquamish, Snoqualmie, and Puyallup, as well as Muckleshoot, Tulalip, other Coast Salish peoples, and their descendants. We are grateful to respectfully live and work as guests on these lands with the Coast Salish and Native people who call this home.

